### ISSUE TITLE
fetch CR name inside the operator controller

### ISSUE THREAD

**Issue by ffoysal** [qlik-oss/qliksense-operator#18]
get the CR name from passing CR inside the controller code. we need it to make association latter on

sample cr
```
apiVersion: qlik.com/v1
kind: Qliksense
metadata:
  name: qliksense-default
  labels:
    version: v0.0.1
spec:
  profile: docker-desktop
  configs:
    qliksense:
    - name: acceptEULA
      value: "yes"
    - name: acceptEULA
      value: "yes"
  manifestsRoot: /Users/mqb/.qliksense/contexts/qliksense-default/qlik-k8s/v0.0.1/manifests
  storageClassName: mokul
  namespace: namespace
```
