### ISSUE TITLE
Create kubernetes operator to install qseok from opeartor

### ISSUE THREAD

**Issue by ffoysal** [qlik-oss/qliksense-operator#20]
From CLI this CR will be passed
```yaml
apiVersion: qlik.com/v1
kind: QlikSense
metadata:
  name: myqliksense
spec:
  profile: manifests/docker-desktop
  git:
    repository: https://github.com/qlik-oss/example-fork?ref=v0.0.1
  namespace: myqliksense
  storageClassName: efs
  configs:
  - qliksense:
    - name: acceptEULA
      value: "yes"
  secrets:
  - qliksense:
    - name: mongoDbUri
      value: "mongo://mongo:3307"
    - name: messagingPassword
      valueFromKey: messagingPassword
```
The operator will fetch config from fork, create kuz patches, install qseok, create PR to the repo
