### ISSUE TITLE
Be able to burn a qliksense-q8s repo into the runner image

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/qliksense-operator#44]
Modify repo watch image to support file system config

**Comment by ffoysal** [comment]
```
apiVersion: qlik.com/v1
kind: Qliksense
metadata:
  name: test-cr  # all the resources are prefixed with this name
  namespace: test-ns
spec:
  profile: base
  manifestsRoot: "/cnab/app"
  storageClassName: efs
  rotateKeys: "yes" 
  git:
    repository: "https://github.com/my-org/qliksense-k8s"
    accessToken: "blalalalal"
  opsRunner:
    enabled: true 
    image: pre-packaged-container:v1.21.23
    watchBranch: master #if both watchBranch and schedule presents then cronjob will be created otherwise a job
    schedule: "*/10 * * * *"
  fetchSource: # used in cli mode
    respository: "http://github.com/my-org/qliksense-k8s"
    accessToken: "something"
  # yes: generate keys and store in k8s, None: use default keys which is in EJSON_KEY env, no: restore key from k8s cluster
  configs:
    qliksense:
    - name: acceptEULA
      value: "yes"
  secrets:
    qliksense:
    - name: mongoDbUri
      value: mongo://mongo:3307
```

**Comment by ffoysal** [comment]
```
  opsRunner:
    enabled: true 
    image: pre-packaged-container:v1.21.23
    crPvc: enabled
```
1. generate patches to tmp/.opeartor fodler
2. create pvc [if storage class in cr use that otherwise empty]
3. run the job with pvc/vloume/volumemount


```
  git:
    repository: "https://github.com/my-org/qliksense-k8s"
    accessToken: "blalalalal"
  opsRunner:
    enabled: true 
    image: pre-packaged-container:v1.21.23
    crPvc: enabled
```
1. pull from gitrepo
2. generate patches to tmp/ fodler
3. create pvc [if storage class in cr use that otherwise empty]
4. run the job with pvc/vloume/volumemount
 
```
git:
    repository: "https://github.com/my-org/qliksense-k8s"
    accessToken: "blalalalal"
```
1. pull from gitrepo
2. generate patches to tmp/ fodler
3. apply to cluster

```
  git:
    repository: "https://github.com/my-org/qliksense-k8s"
    accessToken: "blalalalal"
  opsRunner:
    enabled: true 
    image: pre-packaged-container:v1.21.23
    watchBranch: master 
    schedule: "*/10 * * * *"
    crPvc: enabled
```
1. pull from gitrepo
2. generate patches to tmp/ fodler
3. apply to cluster
4. push new branch to the repo
5. create pvc
5. create cronjob
