### ISSUE TITLE
Role needs '*' verbs

### ISSUE THREAD

**Issue by andriy-bulynko** [qlik-oss/qliksense-operator#57]
`qix-sessions` requires a `role` resource that looks like this:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: qix-sessions
    chart: qix-sessions-4.0.10
    heritage: Helm
    release: qlik-default
  name: qlik-default-qix-sessions
  namespace: default
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  verbs:
  - '*'
- apiGroups:
  - qixmanager.qlik.com
  resources:
  - engines
  - engines/finalizers
  verbs:
  - '*'
```
To be able to create resources like this, we took a shortcut and gave operator a lot of '*' permissions too. Which is not great, especially given that requesting that in the customer environments is not going to be well-received. We need to clean this up.
