### ISSUE TITLE
redesign opsrunner in the operator

### ISSUE THREAD

**Issue by ffoysal** [qlik-oss/qliksense-operator#60]
if cr contains this
```
  git:
    repository: "https://github.com/my-org/qliksense-k8s"
    accessToken: "blalalalal"
  opsRunner:
    enabled: true 
    image: pre-packaged-container:v1.21.23
```
1. Create a kubernetes job and provide CR as environment variable to the job

if cr contains this
```
  git:
    repository: "https://github.com/my-org/qliksense-k8s"
    accessToken: "blalalalal"
  opsRunner:
    enabled: true 
    image: pre-packaged-container:v1.21.23
    watchBranch: master 
    schedule: "*/10 * * * *"
```
1. Create a kubernetes Cronjob and provide Cr as environment variable to the cronjob

if cr contains only this
```
  opsRunner:
    enabled: true 
    image: pre-packaged-container:v1.21.23
    watchBranch: master 
    schedule: "*/10 * * * *"
```
1. Create a kubernetes Cronjob and provide Cr as environment variable to the cronjob

if cr contains only this
```
  git:
    repository: "https://github.com/my-org/qliksense-k8s"
    accessToken: "blalalalal"
```
1. operator does nothing

so the `git` section in the CR actaully to pass into to runner

ADDITIONAL WORK:
1. remove gitpush from k-api while git in the cr
2. remove `pvc` from CR struct as it is not being used
